alter session set "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER pc IDENTIFIED BY kb603 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- QUOTAS
ALTER USER pc QUOTA 1048M ON USERS;

-- ROLES
GRANT DBA,CONNECT,RESOURCE TO pc ;

-- SYSTEM PRIVILEGES