alter session set "_ORACLE_SCRIPT"=true;

SET SERVEROUTPUT ON;
-- USER SQL
CREATE USER PCMANAGEMENT IDENTIFIED BY kb603 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- QUOTAS

-- ROLES
GRANT DBA, CONNECT, RESOURCE TO PCMANAGEMENT;

-- SYSTEM PRIVILEGES

